version: '3'
networks:
  petclinic:
    driver: bridge
services:
  web:
    image: mszcool/springpetclinic:2.0.0.BUILD-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - petclinic
    environment:
      - MYSQL_HOST=jdbc:mysql://mysql/petclinic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=petclinic
    volumes:
      - "/tmp"
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - petclinic
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "/var/lib/mysql"